In [6]:
import numpy as np



In [7]:
arr1 = numpy.array([12,23,45,67,89])
#DUFFERENCE BEETWEEN  array and list is array can stire only one type of data type

In [8]:
arr1

array([12, 23, 45, 67, 89])

In [9]:
print(arr1)

[12 23 45 67 89]


In [10]:
arr2 = np.array([12,14,15,'paras',16.5])

In [11]:
print(arr2)

['12' '14' '15' 'paras' '16.5']


In [12]:
arr2

array(['12', '14', '15', 'paras', '16.5'], dtype='<U32')

In [13]:
%%timeit  #use to measure time taken by code
arr2 = np.array([12,14,15,'paras',16.5])

1.78 µs ± 33.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
arr1.dtype


dtype('int32')

In [15]:
arr2.dtype

dtype('<U32')

In [16]:
arr1.ndim   # gives dimention of array

1

In [17]:
arr2.shape

(5,)

In [20]:
arr1

array([ 27,  38,  60,  82, 104])

In [21]:
arr1 + 15

array([ 42,  53,  75,  97, 119])

In [22]:
#linear equation

x = np.array([23,67,34,21,89])

In [23]:
new1 = x +5.5 + 12
new1

array([ 40.5,  84.5,  51.5,  38.5, 106.5])

In [24]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y = np.arange(10,20)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
y = np.arange(10,25, 0.5)   # list cant have fractional step
y

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5])

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr2d.ndim

2

In [34]:
arr2d.shape

(4, 3)

In [36]:
arr2d.dtype

dtype('int32')

In [37]:
type(arr2d)

numpy.ndarray

In [38]:
arr2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
arr2d.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr2d.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [42]:
arr2d.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [44]:
arr2d.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
arr2d.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr2d.reshape(3,4,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [49]:
arr3d = np.array([
                  [[1,2,3],
                  [4,5,6]],
                  
                   [[7,8,9],
                   [10,11,12]]
                 ])

In [50]:
arr3d.ndim

3

In [51]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Slicing 2d array

In [54]:
arr2d[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [58]:
arr2d[:,0:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [59]:
arr2d[1][1]

5

In [60]:
arr2d[1:2, 1:2]

array([[5]])

In [61]:
arr2d[1,1]

5

In [69]:
arr = np.array([2,4,2,2,5,7,8,5,2,-1])

In [70]:
np.unique(arr)

array([-1,  2,  4,  5,  7,  8])

In [71]:
np.mean(arr)

3.6

In [72]:
np.max(arr)

8

In [73]:
np.abs(arr)

array([2, 4, 2, 2, 5, 7, 8, 5, 2, 1])

In [ ]:
np.